-- Run in the Supabase SQL editor for the project used by this app.
-- This keeps access-code redemption available to the public app without making
-- the underlying entitlement codes enumerable through the anon key.

create table if not exists public.entitlements (
  access_code text primary key,
  access_level text not null check (access_level in ('pro', 'all')),
  expires_at timestamptz
);

alter table public.entitlements
  add column if not exists access_level text,
  add column if not exists expires_at timestamptz;

alter table public.entitlements enable row level security;

do $$
declare
  policy_name text;
begin
  for policy_name in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'entitlements'
  loop
    execute format('drop policy if exists %I on public.entitlements', policy_name);
  end loop;
end $$;

revoke select on public.entitlements from public;
revoke select on public.entitlements from anon, authenticated;

create or replace function public.redeem_access_code(input_code text)
returns table(access_level text, expires_at timestamptz)
language sql
security definer
set search_path = public
stable
as $$
  select e.access_level, e.expires_at
  from public.entitlements e
  where e.access_code = trim(input_code)
    and e.access_level in ('pro', 'all')
  limit 1;
$$;

revoke all on function public.redeem_access_code(text) from public;
grant execute on function public.redeem_access_code(text) to anon;

create table if not exists public.access_code_usage (
  id bigint generated by default as identity primary key,
  access_code text not null,
  status text not null,
  language_id text,
  country text,
  user_agent text,
  created_at timestamptz default now()
);

alter table public.access_code_usage
  add column if not exists access_code text,
  add column if not exists status text,
  add column if not exists language_id text,
  add column if not exists country text,
  add column if not exists user_agent text,
  add column if not exists created_at timestamptz default now();

alter table public.access_code_usage
  drop constraint if exists access_code_usage_status_check;

alter table public.access_code_usage
  add constraint access_code_usage_status_check
  check (status in ('success', 'invalid', 'error'));

alter table public.access_code_usage enable row level security;

drop policy if exists "Allow anonymous access-code usage inserts" on public.access_code_usage;

create policy "Allow anonymous access-code usage inserts"
on public.access_code_usage
for insert
to anon
with check (status in ('success', 'invalid', 'error'));

notify pgrst, 'reload schema';
