import {node} from './masteryFeedbackUI.js';
const copy={
 en:{episode:'Episode',turn:'Moment',title:'Task practice',next:'Next scripted moment',finish:'Finish episode · rate',pass:'Pass episode',rate:'Rate this episode',nextEpisode:'Next episode',plan:'4 episodes · 3 scripted moments each',script:'Each moment is scripted; it does not show how the live response worked.',critical:'Critical part',experiencing:'Experiencing self',position:'Client position',workflow:'This episode',read:'Client reads in the shown position',respond:'Therapist responds',advance:'Guide opens the next scripted moment',feedback:'Client feedback · observer coaching',retry:'Repeat this final moment · therapist retries',rating:'Rate the episode',retryNote:'After the final response: feedback, one retry of this moment, then finish.',guide:'Your part',preview:{client:'Read · listen · change position',therapist:'Listen · guide · respect choice',observer:'Follow · advance · coach',passive:'Watch · give space'},parts:{client:'Read each scripted line as written. You voice both parts of Sara; change position when the label changes.',therapist:'Respond to the moment shown. Keep the positions clear and respect the client’s pace or wish to stop.',observer:'Open the next moment after the response. After the third, guide feedback and retry, then finish and rate the episode.',passive:'Follow the positions and pace. Leave advancement and feedback to the active guide.'},pair:'You guide the moments and assess yourself after the episode.',example:'See an example',hide:'Hide example'},
 no:{episode:'Episode',turn:'Øyeblikk',title:'Oppgaveøving',next:'Neste manusøyeblikk',finish:'Fullfør episoden · vurder',pass:'Stå over episoden',rate:'Vurder episoden',nextEpisode:'Neste episode',plan:'4 episoder · 3 manusøyeblikk i hver',script:'Hvert øyeblikk følger manus; det viser ikke virkningen av svaret som ble gitt.',critical:'Kritisk del',experiencing:'Opplevende del',position:'Klientens posisjon',workflow:'Denne episoden',read:'Klienten leser fra posisjonen som vises',respond:'Terapeuten svarer',advance:'Veilederen åpner neste manusøyeblikk',feedback:'Klientrespons · observatøren veileder',retry:'Gjenta siste øyeblikk · terapeuten prøver igjen',rating:'Vurder episoden',retryNote:'Etter det siste svaret: tilbakemelding, ett nytt forsøk på dette øyeblikket, og så fullføring.',guide:'Din del',preview:{client:'Les · lytt · bytt posisjon',therapist:'Lytt · veiled · gi valgfrihet',observer:'Følg · gå videre · veiled',passive:'Følg med · gi plass'},parts:{client:'Les hvert manusutsagn slik det står. Du gir stemme til begge deler av Sara; bytt posisjon når navnet på posisjonen endres.',therapist:'Svar på øyeblikket som vises. Hold posisjonene tydelige og respekter klientens tempo eller ønske om å stoppe.',observer:'Åpne neste øyeblikk etter svaret. Etter det tredje veileder du tilbakemelding og nytt forsøk, og fullfører og vurderer episoden.',passive:'Følg posisjonene og tempoet. La den aktive veilederen stå for fremdrift og tilbakemelding.'},pair:'Du leder øyeblikkene og vurderer deg selv etter episoden.',example:'Se et eksempel',hide:'Skjul eksempelet'}
};
export const taskCopy=language=>copy[language]??copy.en;
export function createTaskPosition(scene,language){const s=taskCopy(language),n=node('p',`${s.position}: ${s[scene.position]}`,'room-role-badge');n.dataset.taskPosition=scene.position;return n;}
export function createTaskWorkflow({language,last,pair=false}){
 const s=taskCopy(language),d=node('details','', 'room-workflow-guide');d.append(node('summary',s.workflow));
 const list=node('ol','', 'room-workflow');
 const steps=[s.read,s.respond,...(last?[pair?(language==='no'?'Klientens tilbakemelding':'Client feedback'):s.feedback,s.retry,s.rating]:[s.advance])];
 steps.forEach((text,i)=>{const n=node('li');n.append(node('span',String(i+1),'room-workflow-number'),node('span',text));list.append(n);});list.setAttribute('aria-label',s.workflow);d.append(list,node('p',s.script,'response-hint'));return d;
}
export function createTaskRoleGuide({language,role,last,pair=false,example,id,open=false,onToggle}){
 const s=taskCopy(language),d=node('details','', 'room-role-guide');if(id)d.id=id;d.dataset.role=role;d.open=open;if(onToggle)d.addEventListener('toggle',()=>onToggle(d.open));
 const summary=node('summary'),label=node('span');label.append(node('strong',s.guide),node('small',s.preview[role]));summary.append(label);d.append(summary);const body=node('div','', 'room-role-guide-body');body.append(node('p',s.parts[role]));
 if(role==='therapist'&&pair)body.append(node('p',s.pair));
 if(last)body.append(node('p',s.retryNote,'response-hint'));
 if(role==='therapist'&&example){
  const b=node('button',s.example,'ghost-button'),text=node('p',example,'room-example-text');b.type='button';text.hidden=true;text.id=(id??'task-guide')+'-example';b.setAttribute('aria-controls',text.id);b.setAttribute('aria-expanded','false');
  b.addEventListener('click',()=>{text.hidden=!text.hidden;b.textContent=text.hidden?s.example:s.hide;b.setAttribute('aria-expanded',String(!text.hidden));});body.append(b,text);
 }d.append(body);return d;
}
